export const LOGIN_ROUTES = '/login'
export const REGISTRATION_ROUTES = '/registration'
export const ABOUT_ROUTES = '/about'
export const WORKOUT_ROUTES = '/workout'
export const LIST_MODULE_ROUTES = '/listModule'
export const MODULE_ROUTES = '/module'
