export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ABOUT_ROUTE = '/about'
export const WORKOUT_ROUTE = '/workout'
export const LIST_MODULE_ROUTE = '/module_list'
export const MODULE_ROUTE = '/module'
